["CT report"."Insecurity models".0x004517c7.public]
fs_base = ["0x000000000054ba05"]
pk = ["0x000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000"]
r12 = ["0x0000000000000000"]
r13 = ["0x0000000000000000"]
rax = ["0x0000000000000000"]
rbp = ["0x0000000000000000"]
rbx = ["0x0000000000000000"]
rdx = ["0x0000000000000000"]
["CT report"."Insecurity models".0x004517c7.secret1]
sk = ["0x000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000"]
["CT report"."Insecurity models".0x004517c7.secret2]
sk = ["0x0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000ff"]
["CT report"."Insecurity models".0x00451802.public]
fs_base = ["0x7ffefffffffff50e"]
pk = ["0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff"]
r12 = ["0xffffffffffffffff"]
r13 = ["0xffffffffffffffff"]
rax = ["0xffffffffffffffff"]
rbp = ["0xffffffffffffffff"]
rbx = ["0xffffffffffffffff"]
["CT report"."Insecurity models".0x00451802.secret1]
sk = ["0xfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffeffff"]
["CT report"."Insecurity models".0x00451802.secret2]
sk = ["0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff"]
["CT report"."Insecurity models".0x004518be.public]
fs_base = ["0x000000000054ba05"]
pk = ["0x000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000"]
r12 = ["0x0000000000000000"]
r13 = ["0x0000000000000000"]
rax = ["0x0000000000000000"]
rbp = ["0x0000000000000000"]
rbx = ["0x0000000000000000"]
["CT report"."Insecurity models".0x004518be.secret1]
sk = ["0x000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000"]
["CT report"."Insecurity models".0x004518be.secret2]
sk = ["0x0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000ff"]
["CT report"."Insecurity models".0x00475edb.public]
fs_base = ["0x000000000054ba0a"]
pk = ["0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff"]
r12 = ["0xffffffffffffffff"]
r13 = ["0xffffffffffffffff"]
rax = ["0xffffffffffffffff"]
rbp = ["0xffffffffffffffff"]
rbx = ["0xffffffffffffffff"]
["CT report"."Insecurity models".0x00475edb.secret1]
sk = ["0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff01000000ffff"]
["CT report"."Insecurity models".0x00475edb.secret2]
sk = ["0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff01000000feff"]
["CT report"."Insecurity models".0x00475ee2.public]
fs_base = ["0x000000000054ba0a"]
pk = ["0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff"]
r12 = ["0xffffffffffffffff"]
r13 = ["0xffffffffffffffff"]
rax = ["0xfefffffffff50fff"]
rbp = ["0xffffffffffffffff"]
rbx = ["0xffffffffffffffff"]
["CT report"."Insecurity models".0x00475ee2.secret1]
sk = ["0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff010000007efe"]
["CT report"."Insecurity models".0x00475ee2.secret2]
sk = ["0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff010000007ffe"]
["CT report"."Insecurity models".0x00475eea.public]
fs_base = ["0x000000000054b71f"]
pk = ["0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff"]
r12 = ["0xcfffffffffffffff"]
r13 = ["0xffffffffffffffff"]
rax = ["0xffffffffffffffff"]
rbp = ["0xffffffffffffffff"]
rbx = ["0xffffffffffffffff"]
["CT report"."Insecurity models".0x00475eea.secret1]
sk = ["0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffcfffffffffffcfcf"]
["CT report"."Insecurity models".0x00475eea.secret2]
sk = ["0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffdfffffffffffdfdf"]
["CT report"."Insecurity models".0x00475efb.public]
fs_base = ["0x000000000054ba0a"]
pk = ["0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff"]
r12 = ["0xffffffffffffffff"]
r13 = ["0xffffffffffffffff"]
rax = ["0xffffffffffffffff"]
rbp = ["0xffffffffffffffff"]
rbx = ["0xffffffffffffffff"]
["CT report"."Insecurity models".0x00475efb.secret1]
sk = ["0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff01000000feff"]
["CT report"."Insecurity models".0x00475efb.secret2]
sk = ["0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff01000000ffff"]
["CT report"."Instructions status"]
insecure = ["0x004517c7", "0x00451802", "0x004518be", "0x00475edb", "0x00475ee2", "0x00475eea", "0x00475efb"]
unknown = []
[Exploration]
"branching points" = 20
"competed/cut paths" = 16
"failed assertions" = 0
"max path depth" = 80
"pending paths" = 0
"stale paths" = 8
"total paths" = 24
"visited instructions (unrolled)" = 156
["State statistics"."CT checks"]
"Solver time" = 2.58592581749
["State statistics"."CT checks"."Control flow checks"]
"insecure (CV)" = 0
"insecure (RelSE)" = 5
"secure (RelSE)" = 4
"secure (taint)" = 6
unknown = 0
["State statistics"."CT checks"."Memory access checks"]
"insecure (CV)" = 0
"insecure (RelSE)" = 2
"secure (RelSE)" = 1
"secure (taint)" = 61
unknown = 0
["State statistics"."SMT queries"."Preprocessing simplifications"]
"constant enum" = 11
sat = 2
total = 15
unsat = 2
["State statistics"."SMT queries"."Satisfiability queries"]
average = 0.0436635121055
sat = 23
time = 1.00426077843
total = 23
unknown = 0
unsat = 0
