["CT report"."Insecurity models".0x00401c88.public]
fs_base = ["0xffffffffffffffd0"]
pk = ["0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff"]
rbp = ["0xffffffffffffffff"]
["CT report"."Insecurity models".0x00401c88.secret1]
sk = ["0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff7ffeffffffb282cc"]
["CT report"."Insecurity models".0x00401c88.secret2]
sk = ["0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff7ffeffffffb282cd"]
["CT report"."Insecurity models".0x00401cef.public]
fs_base = ["0xffffffffffffffd0"]
pk = ["0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff"]
rbp = ["0xffffffffffffffff"]
["CT report"."Insecurity models".0x00401cef.secret1]
sk = ["0xc0ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff7ffeffffffb282ec"]
["CT report"."Insecurity models".0x00401cef.secret2]
sk = ["0xc0ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff7ffeffffffb282f0"]
["CT report"."Insecurity models".0x0040d211.public]
fs_base = ["0x00000000004d5370"]
pk = ["0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff"]
rbp = ["0xffffffffffffffff"]
["CT report"."Insecurity models".0x0040d211.secret1]
sk = ["0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff7ffeffffffb282e3"]
["CT report"."Insecurity models".0x0040d211.secret2]
sk = ["0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff7ffeffffffb283e4"]
["CT report"."Insecurity models".0x0040d21b.public]
fs_base = ["0x0000000000000000"]
pk = ["0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff"]
rbp = ["0x0000000000000000"]
["CT report"."Insecurity models".0x0040d21b.secret1]
sk = ["0xfefffffffffffffffefffffffffffffffefffffffffffffffefffffffffffffffefffffffffffffffefffffffffffffffefffffffffffffffefffffffffffffffefffffffffffffffefffffffffffffffefffffffffffffffefffffffffffffffefffffffffffffffefffffffffffffffefffffffffffffffefffffffffffffffefffffffffffffffefffffffffffffffe"]
["CT report"."Insecurity models".0x0040d21b.secret2]
sk = ["0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff"]
["CT report"."Insecurity models".0x0040d21e.public]
fs_base = ["0xffffffffffffffd0"]
pk = ["0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff"]
rbp = ["0xffffffffffffffff"]
["CT report"."Insecurity models".0x0040d21e.secret1]
sk = ["0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff7ffeffffffb282c1"]
["CT report"."Insecurity models".0x0040d21e.secret2]
sk = ["0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff7ffeffffffb282c0"]
["CT report"."Insecurity models".0x0040d3e2.public]
fs_base = ["0x0000000000000000"]
pk = ["0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff"]
rbp = ["0x0000000000000000"]
rbx = ["0x0000000000000000"]
["CT report"."Insecurity models".0x0040d3e2.secret1]
sk = ["0xfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffeffffffffffffff"]
["CT report"."Insecurity models".0x0040d3e2.secret2]
sk = ["0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff"]
["CT report"."Insecurity models".0x0040d781.public]
fs_base = ["0xffffffffffffffd0"]
pk = ["0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff00ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff"]
rbp = ["0xffffffffffffffff"]
["CT report"."Insecurity models".0x0040d781.secret1]
sk = ["0xd3ffffffffffffffd5ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff7efeffffffb282d3ffffffffffffffffffffffffffffffff"]
["CT report"."Insecurity models".0x0040d781.secret2]
sk = ["0xd37ffeffffffff82d5fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffefeffffffb282d3ffffffffffffffffffffffffffffffff"]
["CT report"."Insecurity models".0x0040d787.public]
fs_base = ["0xffffffffffffffd0"]
pk = ["0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff00ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff"]
rbp = ["0xffffffffffffffff"]
["CT report"."Insecurity models".0x0040d787.secret1]
sk = ["0xd3ffffffffffffffd5ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff7efeffffffb282d3ffffffffffffffffffffffffffffffff"]
["CT report"."Insecurity models".0x0040d787.secret2]
sk = ["0xd37ffeffffffff82d5fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffefeffffffb282d3ffffffffffffffffffffffffffffffff"]
["CT report"."Insecurity models".0x0040d78c.public]
fs_base = ["0xffffffffffffffd0"]
pk = ["0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff00ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff"]
rbp = ["0xffffffffffffffff"]
["CT report"."Insecurity models".0x0040d78c.secret1]
sk = ["0xd3ffffffffffffffd5ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff7efeffffffb282d3ffffffffffffffffffffffffffffffff"]
["CT report"."Insecurity models".0x0040d78c.secret2]
sk = ["0xd37ffeffffffff82d5fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffefeffffffb282d3ffffffffffffffffffffffffffffffff"]
["CT report"."Insecurity models".0x0040d791.public]
fs_base = ["0xffffffffffffffd0"]
pk = ["0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff00ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff"]
rbp = ["0xffffffffffffffff"]
["CT report"."Insecurity models".0x0040d791.secret1]
sk = ["0xd3ffffffffffffffd5ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff7efeffffffb282d3ffffffffffffffffffffffffffffffff"]
["CT report"."Insecurity models".0x0040d791.secret2]
sk = ["0xd37ffeffffffff82d5fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffefeffffffb282d3ffffffffffffffffffffffffffffffff"]
["CT report"."Insecurity models".0x0040d796.public]
fs_base = ["0xffffffffffffffd0"]
pk = ["0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff00ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff"]
rbp = ["0xffffffffffffffff"]
["CT report"."Insecurity models".0x0040d796.secret1]
sk = ["0xd3ffffffffffffffd5ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff7efeffffffb282d3ffffffffffffffffffffffffffffffff"]
["CT report"."Insecurity models".0x0040d796.secret2]
sk = ["0xd37ffeffffffff82d5fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffefeffffffb282d3ffffffffffffffffffffffffffffffff"]
["CT report"."Insecurity models".0x0040d79b.public]
fs_base = ["0xffffffffffffffd0"]
pk = ["0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff00ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff"]
rbp = ["0xffffffffffffffff"]
["CT report"."Insecurity models".0x0040d79b.secret1]
sk = ["0xd3ffffffffffffffd5ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff7efeffffffb282d3ffffffffffffffffffffffffffffffff"]
["CT report"."Insecurity models".0x0040d79b.secret2]
sk = ["0xd37ffeffffffff82d5fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffefeffffffb282d3ffffffffffffffffffffffffffffffff"]
["CT report"."Insecurity models".0x0040d7a0.public]
fs_base = ["0xffffffffffffffd0"]
pk = ["0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff00ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff"]
rbp = ["0xffffffffffffffff"]
["CT report"."Insecurity models".0x0040d7a0.secret1]
sk = ["0xd3ffffffffffffffd5ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff7efeffffffb282d3ffffffffffffffffffffffffffffffff"]
["CT report"."Insecurity models".0x0040d7a0.secret2]
sk = ["0xd37ffeffffffff82d5fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffefeffffffb282d3ffffffffffffffffffffffffffffffff"]
["CT report"."Instructions status"]
insecure = ["0x00401c88", "0x00401cef", "0x0040d211", "0x0040d21b", "0x0040d21e", "0x0040d3e2", "0x0040d781", "0x0040d787", "0x0040d78c", "0x0040d791", "0x0040d796", "0x0040d79b", "0x0040d7a0"]
unknown = []
[Exploration]
"branching points" = 24
"competed/cut paths" = 6
"failed assertions" = 0
"max path depth" = 176
"pending paths" = 6
"stale paths" = 6
"total paths" = 18
"visited instructions (unrolled)" = 352
["State statistics"."CT checks"]
"Solver time" = 20.2704398632
["State statistics"."CT checks"."Control flow checks"]
"insecure (CV)" = 0
"insecure (RelSE)" = 3
"secure (RelSE)" = 0
"secure (taint)" = 20
unknown = 0
["State statistics"."CT checks"."Memory access checks"]
"insecure (CV)" = 0
"insecure (RelSE)" = 10
"secure (RelSE)" = 0
"secure (taint)" = 140
unknown = 0
["State statistics"."SMT queries"."Preprocessing simplifications"]
"constant enum" = 7
sat = 6
total = 15
unsat = 2
["State statistics"."SMT queries"."Satisfiability queries"]
average = 0.0748136670966
sat = 17
time = 1.42145967484
total = 19
unknown = 0
unsat = 2
